import { DefaultTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#9333ea',
    primaryContainer: '#ede9fe',
    secondary: '#a855f7',
    secondaryContainer: '#f3e8ff',
    tertiary: '#8b5cf6',
    tertiaryContainer: '#e9d5ff',
    background: '#f8fafc',
    surface: '#ffffff',
    surfaceVariant: '#f1f5f9',
    surfaceDisabled: '#f8fafc',
    text: '#1e293b',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onTertiary: '#ffffff',
    onBackground: '#1e293b',
    onSurface: '#1e293b',
    onSurfaceVariant: '#64748b',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    placeholder: '#64748b',
    error: '#ef4444',
    onError: '#ffffff',
    errorContainer: '#fef2f2',
    onErrorContainer: '#dc2626',
    success: '#9333ea',
    onSuccess: '#ffffff',
    successContainer: '#ede9fe',
    onSuccessContainer: '#7c3aed',
    warning: '#f59e0b',
    onWarning: '#ffffff',
    warningContainer: '#fef3c7',
    onWarningContainer: '#d97706',
    elevation: {
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#f8fafc',
      level3: '#f1f5f9',
      level4: '#e2e8f0',
      level5: '#cbd5e1',
    },
  },
  roundness: 12,
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#a855f7',
    primaryContainer: '#7c3aed',
    secondary: '#c084fc',
    secondaryContainer: '#8b5cf6',
    tertiary: '#ddd6fe',
    tertiaryContainer: '#9333ea',
    background: '#0f172a',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    surfaceDisabled: '#1e293b',
    text: '#f1f5f9',
    onPrimary: '#1e1b4b',
    onSecondary: '#312e81',
    onTertiary: '#164e63',
    onBackground: '#f1f5f9',
    onSurface: '#f1f5f9',
    onSurfaceVariant: '#cbd5e1',
    outline: '#64748b',
    outlineVariant: '#475569',
    placeholder: '#94a3b8',
    error: '#f87171',
    onError: '#7f1d1d',
    errorContainer: '#7f1d1d',
    onErrorContainer: '#fecaca',
    success: '#a855f7',
    onSuccess: '#1e1b4b',
    successContainer: '#7c3aed',
    onSuccessContainer: '#ddd6fe',
    warning: '#fbbf24',
    onWarning: '#78350f',
    warningContainer: '#78350f',
    onWarningContainer: '#fde68a',
    elevation: {
      level0: 'transparent',
      level1: '#1e293b',
      level2: '#334155',
      level3: '#475569',
      level4: '#64748b',
      level5: '#94a3b8',
    },
  },
  roundness: 12,
};

// For backward compatibility
export const theme = lightTheme;
